"use client"

import Link from "next/link"
import { useState } from "react"
import { Sidebar } from "@/components/erp/sidebar"
import { Header } from "@/components/erp/header"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Plus, Search, Mail, Calendar, Database, Eye, Edit2, RefreshCw } from "lucide-react"

const apiIntegrations = [{ id: "API-001", name: "그룹웨어 연동", type: "REST API", endpoint: "https://gw.nkia.com/api/v1", description: "그룹웨어 시스템과 결재 연동", status: "활성", lastSync: "2026-03-17 15:30", syncFrequency: "실시간", icon: Calendar }, { id: "API-002", name: "이메일 연동", type: "SMTP/IMAP", endpoint: "mail.nkia.com", description: "이메일 발송 및 수신 알림", status: "활성", lastSync: "2026-03-17 15:45", syncFrequency: "5분", icon: Mail }, { id: "API-003", name: "PIMS 연동", type: "REST API", endpoint: "https://pims.nkia.com/api", description: "프로젝트 관리 시스템 데이터 연동", status: "활성", lastSync: "2026-03-17 14:00", syncFrequency: "1시간", icon: Database }, { id: "API-004", name: "ERP 회계 연동", type: "REST API", endpoint: "https://erp.nkia.com/api/accounting", description: "회계 시스템 데이터 연동", status: "비활성", lastSync: "2026-03-15 10:00", syncFrequency: "일 1회", icon: Database }]
const apiLogs = [{ id: "LOG-20260317-001", apiName: "그룹웨어 연동", action: "결재 상태 조회", timestamp: "2026-03-17 15:30:45", status: "성공", responseTime: "124ms" }]

export default function ApiManagementPage() {
  const [searchTerm, setSearchTerm] = useState("")
  return (
    <div className="min-h-screen bg-background"><Sidebar /><div className="flex-1 flex flex-col"><Header title="API" description="외부 시스템과의 데이터 연동을 관리합니다" />
      <main className="flex-1 overflow-auto p-6"><div className="space-y-6"><div className="grid grid-cols-1 gap-4 md:grid-cols-4"><Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">전체 API</p><p className="text-3xl font-bold">{apiIntegrations.length}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">활성 API</p><p className="text-3xl font-bold text-green-600">{apiIntegrations.filter((a) => a.status === "활성").length}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">오늘 호출 수</p><p className="text-3xl font-bold text-blue-600">1,247</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">오류율</p><p className="text-3xl font-bold text-amber-600">0.8%</p></CardContent></Card></div>
      <Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><div><CardTitle className="text-lg">API 연동 관리</CardTitle><CardDescription>그룹웨어, 이메일, PIMS 등 연계 시스템 관리</CardDescription></div><div className="flex items-center gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 w-4 h-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="검색..." className="w-48 pl-9" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /></div><Button asChild><Link href="/api-management/new"><Plus className="mr-2 w-4 h-4" />API 등록</Link></Button></div></div></CardHeader><CardContent><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{apiIntegrations.map((api) => { const Icon = api.icon; return <Card key={api.id} className="border"><CardContent className="p-4"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${api.status === "활성" ? "bg-green-100" : "bg-gray-100"}`}><Icon className={`w-5 h-5 ${api.status === "활성" ? "text-green-600" : "text-gray-400"}`} /></div><div><div className="flex items-center gap-2"><p className="font-semibold">{api.name}</p><Badge variant={api.status === "활성" ? "default" : "secondary"}>{api.status}</Badge></div><p className="text-sm text-muted-foreground">{api.type}</p></div></div><div className="flex gap-1"><Button variant="ghost" size="icon"><Eye className="w-4 h-4" /></Button><Button variant="ghost" size="icon"><Edit2 className="w-4 h-4" /></Button><Button variant="ghost" size="icon"><RefreshCw className="w-4 h-4" /></Button></div></div><div className="mt-4 space-y-2 text-sm"><p><span className="text-muted-foreground">엔드포인트:</span> {api.endpoint}</p><p><span className="text-muted-foreground">설명:</span> {api.description}</p><p><span className="text-muted-foreground">동기화 주기:</span> {api.syncFrequency}</p><p><span className="text-muted-foreground">마지막 동기화:</span> {api.lastSync}</p></div></CardContent></Card> })}</div></CardContent></Card>
      <Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-lg">API 로그</CardTitle><Badge variant="secondary">{apiLogs.length}건</Badge></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>로그 ID</TableHead><TableHead>API 명</TableHead><TableHead>작업</TableHead><TableHead>시간</TableHead><TableHead>상태</TableHead><TableHead>응답시간</TableHead></TableRow></TableHeader><TableBody>{apiLogs.map((log) => <TableRow key={log.id}><TableCell className="font-mono text-sm">{log.id}</TableCell><TableCell>{log.apiName}</TableCell><TableCell>{log.action}</TableCell><TableCell>{log.timestamp}</TableCell><TableCell><Badge variant={log.status === "성공" ? "default" : "destructive"}>{log.status}</Badge></TableCell><TableCell>{log.responseTime}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></main></div></div>
  )
}
