#!/bin/sh
set -eu

AI_DB_USER="${AI_DB_USER:-orbis_ai}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
GRANT USAGE ON SCHEMA ai TO ${AI_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ai TO ${AI_DB_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ai TO ${AI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA ai GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${AI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA ai GRANT USAGE, SELECT ON SEQUENCES TO ${AI_DB_USER};
SQL
