"use client"

import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Sidebar } from "@/components/erp/sidebar"
import { Header } from "@/components/erp/header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { FilterPopover } from "@/components/erp/filter-popover"
import { defaultFilterValues, filterRecords, type FilterValues, uniqueOptions } from "@/lib/filter-utils"
import { bidResults, bidStatuses, prbList, proposalList, rfpList } from "@/lib/bid-data"
import { Plus, Search, FileText, ClipboardCheck, Presentation, Trophy } from "lucide-react"

export default function BidPage() {
  const router = useRouter()
  const [searchTerm, setSearchTerm] = useState("")
  const [filters, setFilters] = useState<FilterValues>(defaultFilterValues)
  const [activeTab, setActiveTab] = useState<"rfp" | "prb" | "proposal" | "result">("rfp")
  const q = searchTerm.toLowerCase()
  const bidFieldOptions = activeTab === "rfp"
    ? [{ key: "customer", label: "고객사", options: uniqueOptions(rfpList, (i) => i.customer) }]
    : activeTab === "prb"
    ? [
      { key: "customer", label: "고객사", options: uniqueOptions(prbList, (i) => i.customer) },
      { key: "riskLevel", label: "리스크", options: uniqueOptions(prbList, (i) => i.riskLevel) },
    ]
    : activeTab === "proposal"
      ? [{ key: "customer", label: "고객사", options: uniqueOptions(proposalList, (i) => i.customer) }]
      : [
        { key: "customer", label: "고객사", options: uniqueOptions(bidResults, (i) => i.customer) },
        { key: "competitor", label: "경쟁사", options: uniqueOptions(bidResults, (i) => i.competitor) },
      ]
  const filteredRfpList = filterRecords(rfpList, filters, { status: (i) => i.status, owner: (i) => i.analyst, date: (i) => i.receiveDate, fields: { customer: (i) => i.customer } }).filter((i) => [i.id, i.name, i.customer, i.analyst].join(" ").toLowerCase().includes(q))
  const filteredPrbList = filterRecords(prbList, filters, { status: (i) => i.result, owner: (i) => i.reviewer, date: (i) => i.submitDate, fields: { customer: (i) => i.customer, riskLevel: (i) => i.riskLevel } }).filter((i) => [i.id, i.name, i.customer, i.reviewer].join(" ").toLowerCase().includes(q))
  const filteredProposalList = filterRecords(proposalList, filters, { status: (i) => i.status, owner: (i) => i.manager, date: (i) => i.startDate, fields: { customer: (i) => i.customer } }).filter((i) => [i.id, i.name, i.customer, i.manager].join(" ").toLowerCase().includes(q))
  const filteredBidResults = filterRecords(bidResults, filters, { status: (i) => i.result, owner: (i) => i.salesRep, date: (i) => i.bidDate, fields: { customer: (i) => i.customer, competitor: (i) => i.competitor } }).filter((i) => [i.id, i.name, i.customer, i.salesRep].join(" ").toLowerCase().includes(q))
  return (
    <div className="min-h-screen bg-background"><Sidebar /><div className="flex-1 flex flex-col"><Header title="입찰" description="RFP 분석, PRB 검토, 제안서 작성 및 입찰 결과를 관리합니다" />
      <main className="flex-1 overflow-auto p-6"><Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as "rfp" | "prb" | "proposal" | "result")} className="space-y-6"><div className="flex items-center justify-between"><TabsList><TabsTrigger value="rfp" className="gap-2"><FileText className="w-4 h-4" />RFP</TabsTrigger><TabsTrigger value="prb" className="gap-2"><ClipboardCheck className="w-4 h-4" />PRB</TabsTrigger><TabsTrigger value="proposal" className="gap-2"><Presentation className="w-4 h-4" />제안</TabsTrigger><TabsTrigger value="result" className="gap-2"><Trophy className="w-4 h-4" />입찰 결과</TabsTrigger></TabsList><div className="flex items-center gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 w-4 h-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="검색..." className="w-64 pl-9" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /></div><FilterPopover title="입찰" statusOptions={bidStatuses} value={filters} onApply={setFilters} fieldOptions={bidFieldOptions} /><Button asChild><Link href={`/bid/new/${activeTab}`}><Plus className="mr-2 w-4 h-4" />{activeTab === "rfp" ? "RFP 등록" : activeTab === "prb" ? "PRB 등록" : activeTab === "proposal" ? "제안 등록" : "입찰결과 등록"}</Link></Button></div></div>
      <TabsContent value="rfp"><Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-lg">RFP 목록</CardTitle><Badge variant="secondary">{filteredRfpList.length}건</Badge></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead className="w-[120px]">RFP 번호</TableHead><TableHead>사업명</TableHead><TableHead>고객사</TableHead><TableHead>입수일</TableHead><TableHead>제출마감</TableHead><TableHead>입찰일</TableHead><TableHead className="text-right">예상금액</TableHead><TableHead>상태</TableHead><TableHead>담당자</TableHead></TableRow></TableHeader><TableBody>{filteredRfpList.map((rfp) => <TableRow key={rfp.id} className="cursor-pointer hover:bg-muted/50" onClick={() => router.push(`/bid/rfp/${rfp.id}`)}><TableCell className="font-mono text-sm">{rfp.id}</TableCell><TableCell className="max-w-[200px] truncate font-medium">{rfp.name}</TableCell><TableCell>{rfp.customer}</TableCell><TableCell>{rfp.receiveDate}</TableCell><TableCell>{rfp.dueDate}</TableCell><TableCell>{rfp.bidDate}</TableCell><TableCell className="text-right font-medium">{rfp.amount}</TableCell><TableCell><Badge variant={rfp.status === "분석완료" ? "default" : rfp.status === "분석중" ? "secondary" : "outline"} className={rfp.status === "분석완료" ? "bg-green-100 text-green-700 hover:bg-green-100" : rfp.status === "분석중" ? "bg-blue-100 text-blue-700 hover:bg-blue-100" : "bg-amber-100 text-amber-700 hover:bg-amber-100"}>{rfp.status}</Badge></TableCell><TableCell>{rfp.analyst}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="prb"><Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-lg">PRB 목록</CardTitle><Badge variant="secondary">{filteredPrbList.length}건</Badge></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead className="w-[120px]">PRB 번호</TableHead><TableHead>RFP 번호</TableHead><TableHead>사업명</TableHead><TableHead>고객사</TableHead><TableHead>제출일</TableHead><TableHead>검토일</TableHead><TableHead>리스크</TableHead><TableHead>결과</TableHead><TableHead>검토자</TableHead></TableRow></TableHeader><TableBody>{filteredPrbList.map((prb) => <TableRow key={prb.id} className="cursor-pointer hover:bg-muted/50" onClick={() => router.push(`/bid/prb/${prb.id}`)}><TableCell className="font-mono text-sm">{prb.id}</TableCell><TableCell className="font-mono text-sm">{prb.rfpId}</TableCell><TableCell className="max-w-[200px] truncate font-medium">{prb.name}</TableCell><TableCell>{prb.customer}</TableCell><TableCell>{prb.submitDate}</TableCell><TableCell>{prb.reviewDate}</TableCell><TableCell><Badge variant={prb.riskLevel === "고" ? "destructive" : prb.riskLevel === "중" ? "secondary" : "outline"}>{prb.riskLevel}</Badge></TableCell><TableCell><Badge variant={prb.result === "승인" ? "default" : "outline"} className={prb.result === "승인" ? "bg-green-100 text-green-700 hover:bg-green-100" : "bg-amber-100 text-amber-700 hover:bg-amber-100"}>{prb.result}</Badge></TableCell><TableCell>{prb.reviewer}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="proposal"><Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-lg">제안서 목록</CardTitle><Badge variant="secondary">{filteredProposalList.length}건</Badge></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead className="w-[120px]">제안번호</TableHead><TableHead>RFP 번호</TableHead><TableHead>사업명</TableHead><TableHead>고객사</TableHead><TableHead>작성시작</TableHead><TableHead>제출마감</TableHead><TableHead>진행률</TableHead><TableHead>상태</TableHead><TableHead>PM</TableHead></TableRow></TableHeader><TableBody>{filteredProposalList.map((proposal) => <TableRow key={proposal.id} className="cursor-pointer hover:bg-muted/50" onClick={() => router.push(`/bid/proposal/${proposal.id}`)}><TableCell className="font-mono text-sm">{proposal.id}</TableCell><TableCell className="font-mono text-sm">{proposal.rfpId}</TableCell><TableCell className="max-w-[200px] truncate font-medium">{proposal.name}</TableCell><TableCell>{proposal.customer}</TableCell><TableCell>{proposal.startDate}</TableCell><TableCell>{proposal.dueDate}</TableCell><TableCell>{proposal.progress}%</TableCell><TableCell><Badge className="bg-blue-100 text-blue-700 hover:bg-blue-100">{proposal.status}</Badge></TableCell><TableCell>{proposal.manager}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="result"><Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-lg">입찰 결과 목록</CardTitle><Badge variant="secondary">{filteredBidResults.length}건</Badge></div></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead className="w-[120px]">입찰번호</TableHead><TableHead>사업명</TableHead><TableHead>고객사</TableHead><TableHead>입찰일</TableHead><TableHead className="text-right">금액</TableHead><TableHead>경쟁사</TableHead><TableHead>결과</TableHead><TableHead>사유</TableHead><TableHead>담당자</TableHead></TableRow></TableHeader><TableBody>{filteredBidResults.map((bid) => <TableRow key={bid.id} className="cursor-pointer hover:bg-muted/50" onClick={() => router.push(`/bid/result/${bid.id}`)}><TableCell className="font-mono text-sm">{bid.id}</TableCell><TableCell className="max-w-[180px] truncate font-medium">{bid.name}</TableCell><TableCell>{bid.customer}</TableCell><TableCell>{bid.bidDate}</TableCell><TableCell className="text-right font-medium">{bid.amount}</TableCell><TableCell>{bid.competitor}</TableCell><TableCell><Badge variant={bid.result === "수주" ? "default" : "destructive"} className={bid.result === "수주" ? "bg-green-100 text-green-700 hover:bg-green-100" : ""}>{bid.result}</Badge></TableCell><TableCell className="max-w-[150px] truncate">{bid.result === "수주" ? bid.winReason : bid.loseReason}</TableCell><TableCell>{bid.salesRep}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      </Tabs></main></div></div>
  )
}
